name: Renovate dependencies

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      RENOVATE_BRANCH_NAME:
        description: Branch name passed to Renovate
        type: string
        required: false

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}

      - name: Generate Renovate app token
        id: renovate-app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}
          repositories: ${{ toJSON(github.repository) }}

      - name: Prepare Renovate env
        if: inputs.RENOVATE_BRANCH_NAME
        run: echo "RENOVATE_BRANCH_NAME=${{ inputs.RENOVATE_BRANCH_NAME }}" >> $GITHUB_ENV

      - name: Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          token: ${{ steps.renovate-app-token.outputs.token }}
        env:
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: ${{ github.repository }}
          RENOVATE_AUTOMERGE: true
          RENOVATE_PR_HOURLY_LIMIT: 0
