name: Build and Push

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build image and push to container registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - alpine
        alpine_version:
          - 3.16
          - 3.17
          - 3.18
        include:
          - target: scratch
            alpine_version: 3.18
            latest: true
          - alpine_version: 3.18
            latest: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to container registry
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: TARGET=${{ matrix.target }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ matrix.target == 'alpine' && format('ghcr.io/{0}:{1}-{2}{3}', github.repository, github.ref_name, matrix.target, matrix.alpine_version) || '' }}
            ${{ matrix.target == 'alpine' && format('ghcr.io/{0}:{1}-{2}{3}', github.repository, github.ref_name, matrix.target, matrix.alpine_version) || '' }}
            ${{ matrix.latest == true && format('ghcr.io/{0}:{1}-{2}', github.repository, github.ref_name, matrix.target) || '' }}
            ${{ matrix.latest == true && format('ghcr.io/{0}:{1}-{2}', github.repository, 'latest', matrix.target) || '' }}
            ${{ matrix.latest == true && matrix.target == 'alpine' && format('ghcr.io/{0}:{1}', github.repository, github.ref_name) || '' }}
            ${{ matrix.latest == true && matrix.target == 'alpine' && format('ghcr.io/{0}:{1}', github.repository, 'latest') || '' }}
