name: Pull request updated

on:
  merge_group:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yaml

  auto-merge:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}

      - name: Auto merge
        run: gh pr merge ${{ steps.extract-ref.outputs.ref }} --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pull-request-merged:
    needs:
      - auto-merge
    uses: ./.github/workflows/pull-request-merged.yaml
