name: Run tests

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      ref:
        description: Ref (default HEAD)
        type: string

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || steps.extract-ref.outputs.ref }}

      - name: Build image and run tests
        shell: bash
        run: |
          exit 0
